/* =====================
   WEALTHLENS – DATA.JS
   All asset data with historical CAGR estimates
   ===================== */

const ALL_ASSETS = {
  stocks: [
    {sym:'RELIANCE',   name:'Reliance Industries',         sector:'Energy',         cagr:18.4},
    {sym:'TCS',        name:'Tata Consultancy Services',   sector:'IT',             cagr:20.1},
    {sym:'HDFCBANK',   name:'HDFC Bank',                   sector:'Banking',        cagr:16.7},
    {sym:'INFY',       name:'Infosys',                     sector:'IT',             cagr:17.2},
    {sym:'ICICIBANK',  name:'ICICI Bank',                  sector:'Banking',        cagr:18.9},
    {sym:'HINDUNILVR', name:'Hindustan Unilever',          sector:'FMCG',           cagr:14.3},
    {sym:'ITC',        name:'ITC Limited',                 sector:'FMCG',           cagr:12.1},
    {sym:'SBIN',       name:'State Bank of India',         sector:'Banking',        cagr:13.5},
    {sym:'BHARTIARTL', name:'Bharti Airtel',               sector:'Telecom',        cagr:15.8},
    {sym:'KOTAKBANK',  name:'Kotak Mahindra Bank',         sector:'Banking',        cagr:19.4},
    {sym:'LT',         name:'Larsen & Toubro',             sector:'Infrastructure', cagr:14.7},
    {sym:'AXISBANK',   name:'Axis Bank',                   sector:'Banking',        cagr:14.2},
    {sym:'ASIANPAINT', name:'Asian Paints',                sector:'Paints',         cagr:21.3},
    {sym:'MARUTI',     name:'Maruti Suzuki',               sector:'Auto',           cagr:16.5},
    {sym:'SUNPHARMA',  name:'Sun Pharmaceutical',          sector:'Pharma',         cagr:15.9},
    {sym:'TITAN',      name:'Titan Company',               sector:'Consumer',       cagr:24.6},
    {sym:'BAJFINANCE', name:'Bajaj Finance',               sector:'NBFC',           cagr:32.1},
    {sym:'WIPRO',      name:'Wipro',                       sector:'IT',             cagr:13.8},
    {sym:'HCLTECH',    name:'HCL Technologies',            sector:'IT',             cagr:18.6},
    {sym:'ULTRACEMCO', name:'UltraTech Cement',            sector:'Cement',         cagr:17.1},
    {sym:'NESTLEIND',  name:'Nestle India',                sector:'FMCG',           cagr:18.4},
    {sym:'POWERGRID',  name:'Power Grid Corp',             sector:'Utilities',      cagr:13.2},
    {sym:'NTPC',       name:'NTPC',                        sector:'Power',          cagr:11.8},
    {sym:'ONGC',       name:'Oil & Natural Gas Corp',      sector:'Energy',         cagr:8.7},
    {sym:'COALINDIA',  name:'Coal India',                  sector:'Mining',         cagr:9.4},
    {sym:'TATAMOTORS', name:'Tata Motors',                 sector:'Auto',           cagr:14.8},
    {sym:'TATASTEEL',  name:'Tata Steel',                  sector:'Metals',         cagr:10.3},
    {sym:'JSWSTEEL',   name:'JSW Steel',                   sector:'Metals',         cagr:16.2},
    {sym:'HINDALCO',   name:'Hindalco Industries',         sector:'Metals',         cagr:13.7},
    {sym:'DRREDDY',    name:"Dr. Reddy's Labs",            sector:'Pharma',         cagr:14.5},
    {sym:'CIPLA',      name:'Cipla',                       sector:'Pharma',         cagr:13.1},
    {sym:'DIVISLAB',   name:"Divi's Laboratories",         sector:'Pharma',         cagr:22.8},
    {sym:'EICHERMOT',  name:'Eicher Motors',               sector:'Auto',           cagr:28.4},
    {sym:'BAJAJ-AUTO', name:'Bajaj Auto',                  sector:'Auto',           cagr:17.3},
    {sym:'HEROMOTOCO', name:'Hero MotoCorp',               sector:'Auto',           cagr:13.6},
    {sym:'M&M',        name:'Mahindra & Mahindra',         sector:'Auto',           cagr:16.1},
    {sym:'ADANIENT',   name:'Adani Enterprises',           sector:'Conglomerate',   cagr:29.7},
    {sym:'ADANIPORTS', name:'Adani Ports',                 sector:'Infrastructure', cagr:24.3},
    {sym:'ADANIGREEN', name:'Adani Green Energy',          sector:'Renewables',     cagr:38.2},
    {sym:'SIEMENS',    name:'Siemens India',               sector:'Industrials',    cagr:18.9},
    {sym:'ABB',        name:'ABB India',                   sector:'Industrials',    cagr:21.4},
    {sym:'HAVELLS',    name:'Havells India',               sector:'Electricals',    cagr:22.7},
    {sym:'PIDILITIND', name:'Pidilite Industries',         sector:'Chemicals',      cagr:22.1},
    {sym:'BERGEPAINT', name:'Berger Paints',               sector:'Paints',         cagr:19.8},
    {sym:'PAGEIND',    name:'Page Industries',             sector:'Textiles',       cagr:26.3},
    {sym:'MUTHOOTFIN', name:'Muthoot Finance',             sector:'NBFC',           cagr:23.5},
    {sym:'CHOLAFIN',   name:'Cholamandalam Finance',       sector:'NBFC',           cagr:27.8},
    {sym:'SBILIFE',    name:'SBI Life Insurance',          sector:'Insurance',      cagr:19.6},
    {sym:'HDFCLIFE',   name:'HDFC Life Insurance',         sector:'Insurance',      cagr:17.9},
    {sym:'ICICIPRU',   name:'ICICI Prudential Life',       sector:'Insurance',      cagr:15.3},
    {sym:'GRASIM',     name:'Grasim Industries',           sector:'Conglomerate',   cagr:14.8},
    {sym:'INDUSINDBK', name:'IndusInd Bank',               sector:'Banking',        cagr:18.7},
    {sym:'BANDHANBNK', name:'Bandhan Bank',                sector:'Banking',        cagr:14.1},
    {sym:'FEDERALBNK', name:'Federal Bank',                sector:'Banking',        cagr:13.4},
    {sym:'IDFCFIRSTB', name:'IDFC First Bank',             sector:'Banking',        cagr:11.6},
    {sym:'PNB',        name:'Punjab National Bank',        sector:'Banking',        cagr:7.3},
    {sym:'BANKBARODA', name:'Bank of Baroda',              sector:'Banking',        cagr:8.9},
    {sym:'CANBK',      name:'Canara Bank',                 sector:'Banking',        cagr:8.4},
    {sym:'RECLTD',     name:'REC Limited',                 sector:'Finance',        cagr:16.3},
    {sym:'PFC',        name:'Power Finance Corp',          sector:'Finance',        cagr:15.7},
    {sym:'IRFC',       name:'Indian Railway Finance',      sector:'Finance',        cagr:17.2},
    {sym:'HDFCAMC',    name:'HDFC AMC',                    sector:'Finance',        cagr:20.4},
    {sym:'NAUKRI',     name:'Info Edge (Naukri)',           sector:'Internet',       cagr:28.6},
    {sym:'ZOMATO',     name:'Zomato',                      sector:'Internet',       cagr:22.3},
    {sym:'DMART',      name:'Avenue Supermarts (DMart)',   sector:'Retail',         cagr:31.2},
    {sym:'TRENT',      name:'Trent (Westside)',            sector:'Retail',         cagr:35.7},
    {sym:'JUBLFOOD',   name:'Jubilant FoodWorks',          sector:'QSR',            cagr:23.4},
    {sym:'ZYDUSLIFE',  name:'Zydus Lifesciences',          sector:'Pharma',         cagr:16.8},
    {sym:'AUROPHARMA', name:'Aurobindo Pharma',            sector:'Pharma',         cagr:14.2},
    {sym:'TORNTPHARM', name:'Torrent Pharma',              sector:'Pharma',         cagr:17.6},
    {sym:'ALKEM',      name:'Alkem Laboratories',          sector:'Pharma',         cagr:18.9},
    {sym:'LUPIN',      name:'Lupin',                       sector:'Pharma',         cagr:11.3},
    {sym:'ABBOTINDIA', name:'Abbott India',                sector:'Pharma',         cagr:19.2},
    {sym:'TATAPOWER',  name:'Tata Power',                  sector:'Power',          cagr:15.4},
    {sym:'ADANIPOWER', name:'Adani Power',                 sector:'Power',          cagr:31.6},
    {sym:'TORNTPOWER', name:'Torrent Power',               sector:'Power',          cagr:16.7},
    {sym:'GUJGASLTD',  name:'Gujarat Gas',                 sector:'Gas',            cagr:22.3},
    {sym:'IGL',        name:'Indraprastha Gas',            sector:'Gas',            cagr:19.8},
    {sym:'MGL',        name:'Mahanagar Gas',               sector:'Gas',            cagr:17.4},
    {sym:'BPCL',       name:'BPCL',                        sector:'Oil & Gas',      cagr:12.6},
    {sym:'HPCL',       name:'HPCL',                        sector:'Oil & Gas',      cagr:10.8},
    {sym:'IOC',        name:'Indian Oil Corp',             sector:'Oil & Gas',      cagr:9.3},
    {sym:'GAIL',       name:'GAIL India',                  sector:'Gas',            cagr:10.7},
    {sym:'TATACOMM',   name:'Tata Communications',         sector:'Telecom',        cagr:17.8},
    {sym:'IRCTC',      name:'IRCTC',                       sector:'Travel',         cagr:29.4},
    {sym:'CONCOR',     name:'Container Corp of India',     sector:'Logistics',      cagr:12.8},
    {sym:'BLUEDART',   name:'Blue Dart Express',           sector:'Logistics',      cagr:16.2},
    {sym:'OBEROIRLTY', name:'Oberoi Realty',               sector:'Real Estate',    cagr:18.4},
    {sym:'GODREJPROP', name:'Godrej Properties',           sector:'Real Estate',    cagr:21.7},
    {sym:'DLF',        name:'DLF',                         sector:'Real Estate',    cagr:12.3},
    {sym:'PRESTIGE',   name:'Prestige Estates',            sector:'Real Estate',    cagr:19.6},
    {sym:'ACC',        name:'ACC',                         sector:'Cement',         cagr:12.4},
    {sym:'AMBUJACEM',  name:'Ambuja Cements',              sector:'Cement',         cagr:13.1},
    {sym:'SHREECEM',   name:'Shree Cement',                sector:'Cement',         cagr:20.8},
    {sym:'BOSCHLTD',   name:'Bosch',                       sector:'Auto Ancillary', cagr:15.8},
    {sym:'MOTHERSON',  name:'Samvardhana Motherson',       sector:'Auto Ancillary', cagr:18.2},
    {sym:'APOLLOTYRE', name:'Apollo Tyres',                sector:'Auto Ancillary', cagr:13.4},
    {sym:'MRF',        name:'MRF',                         sector:'Tyres',          cagr:16.8},
    {sym:'BALKRISIND', name:'Balkrishna Industries',       sector:'Tyres',          cagr:24.3},
    {sym:'TVSMOTOR',   name:'TVS Motor',                   sector:'Auto',           cagr:21.8},
    {sym:'SRTRANSFIN', name:'Shriram Finance',             sector:'NBFC',           cagr:19.2},
    {sym:'MANAPPURAM', name:'Manappuram Finance',          sector:'NBFC',           cagr:21.6},
    {sym:'LICHSGFIN',  name:'LIC Housing Finance',         sector:'NBFC',           cagr:12.8},
    {sym:'CANFINHOME', name:'Can Fin Homes',               sector:'NBFC',           cagr:22.4},
    {sym:'PAYTM',      name:'One97 Communications (Paytm)',sector:'Fintech',        cagr:-8.4},
    {sym:'IDEA',       name:'Vodafone Idea',               sector:'Telecom',        cagr:-18.7},
    {sym:'MTNL',       name:'MTNL',                        sector:'Telecom',        cagr:-12.3},
  ],
  indices: [
    {sym:'NIFTY50',    name:'Nifty 50',              sector:'Broad Index',    cagr:14.2},
    {sym:'SENSEX',     name:'BSE Sensex',            sector:'Broad Index',    cagr:13.8},
    {sym:'NIFTY500',   name:'Nifty 500',             sector:'Broad Index',    cagr:15.1},
    {sym:'NIFTYMID',   name:'Nifty Midcap 100',      sector:'Broad Index',    cagr:16.4},
    {sym:'NIFTYSML',   name:'Nifty Smallcap 100',    sector:'Broad Index',    cagr:14.8},
    {sym:'NIFTYIT',    name:'Nifty IT',              sector:'Sectoral Index', cagr:18.6},
    {sym:'NIFTYBK',    name:'Nifty Bank',            sector:'Sectoral Index', cagr:16.2},
    {sym:'NIFTYPHRM',  name:'Nifty Pharma',          sector:'Sectoral Index', cagr:14.7},
    {sym:'NIFTYAUTO',  name:'Nifty Auto',            sector:'Sectoral Index', cagr:15.3},
    {sym:'NIFTYFMCG',  name:'Nifty FMCG',           sector:'Sectoral Index', cagr:13.9},
    {sym:'NIFTYINFRA', name:'Nifty Infrastructure',  sector:'Sectoral Index', cagr:13.1},
    {sym:'NIFTYREALTY',name:'Nifty Realty',          sector:'Sectoral Index', cagr:14.6},
    {sym:'NIFTYMETAL', name:'Nifty Metal',           sector:'Sectoral Index', cagr:11.8},
    {sym:'NIFTYENERGY',name:'Nifty Energy',          sector:'Sectoral Index', cagr:12.4},
  ],
  commodities: [
    {sym:'GOLD',       name:'Gold (MCX)',        sector:'Precious Metal', cagr:10.5},
    {sym:'SILVER',     name:'Silver (MCX)',      sector:'Precious Metal', cagr:7.2},
    {sym:'CRUDEOIL',   name:'Crude Oil (MCX)',   sector:'Energy',         cagr:4.8},
    {sym:'NATURALGAS', name:'Natural Gas (MCX)', sector:'Energy',         cagr:2.3},
    {sym:'COPPER',     name:'Copper (MCX)',      sector:'Base Metal',     cagr:8.6},
    {sym:'ZINC',       name:'Zinc (MCX)',        sector:'Base Metal',     cagr:7.1},
    {sym:'ALUMINIUM',  name:'Aluminium (MCX)',   sector:'Base Metal',     cagr:5.4},
    {sym:'NICKEL',     name:'Nickel (MCX)',      sector:'Base Metal',     cagr:6.2},
  ],
  realestate: [
    {sym:'RE-MUM', name:'Real Estate – Mumbai',     sector:'Residential RE', cagr:8.9},
    {sym:'RE-DEL', name:'Real Estate – Delhi NCR',  sector:'Residential RE', cagr:7.8},
    {sym:'RE-BLR', name:'Real Estate – Bengaluru',  sector:'Residential RE', cagr:10.1},
    {sym:'RE-HYD', name:'Real Estate – Hyderabad',  sector:'Residential RE', cagr:11.4},
    {sym:'RE-CHN', name:'Real Estate – Chennai',    sector:'Residential RE', cagr:8.3},
    {sym:'RE-PUN', name:'Real Estate – Pune',       sector:'Residential RE', cagr:9.6},
    {sym:'RE-KOL', name:'Real Estate – Kolkata',    sector:'Residential RE', cagr:7.2},
    {sym:'RE-AHM', name:'Real Estate – Ahmedabad',  sector:'Residential RE', cagr:10.8},
    {sym:'RE-SUR', name:'Real Estate – Surat',      sector:'Residential RE', cagr:9.3},
    {sym:'RE-LKN', name:'Real Estate – Lucknow',    sector:'Residential RE', cagr:8.7},
  ]
};

const PALETTE = [
  '#3C3489','#C9A84C','#1D9E75','#D85A30','#185FA5',
  '#993556','#639922','#534AB7','#A32D2D','#0F6E56',
  '#BA7517','#D4537E','#3B6D11','#888780','#85B7EB','#EF9F27'
];
